In [2]:
import numpy as np
from numpy.random import rand
import matplotlib.pyplot as plt

def inicio(n,m):   
    #genera una matriz de n x m con valores aleatorios -1 y 1
    estadoinicial = 2*np.random.randint(2, size=(n,m))-1
    return estadoinicial

#prueba
a1=inicio(7,22)
print(a1)
config=inicio(25,25)
print(config)

[[ 1  1  1  1  1 -1  1  1 -1 -1  1  1 -1 -1 -1  1  1 -1  1  1  1  1]
 [-1  1 -1 -1 -1  1 -1 -1 -1 -1  1  1 -1  1  1 -1  1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1  1 -1  1  1 -1 -1 -1  1  1  1  1 -1 -1 -1  1  1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1 -1 -1  1  1 -1 -1 -1  1 -1 -1 -1  1 -1  1 -1]
 [ 1  1 -1  1  1 -1  1  1 -1  1 -1  1  1 -1 -1 -1  1 -1 -1 -1  1  1]
 [ 1 -1 -1 -1 -1  1 -1  1  1 -1 -1 -1  1 -1  1  1 -1 -1  1  1 -1 -1]
 [ 1  1  1  1 -1 -1  1  1 -1 -1  1  1  1 -1  1 -1 -1 -1  1 -1  1  1]]
[[-1  1  1  1 -1 -1  1  1  1  1 -1 -1  1  1  1 -1  1 -1 -1  1 -1 -1  1  1
   1]
 [ 1  1 -1  1 -1  1  1 -1 -1  1 -1 -1  1  1  1  1  1 -1  1 -1  1 -1 -1  1
  -1]
 [-1  1 -1 -1  1 -1  1 -1  1 -1 -1 -1 -1  1  1  1  1 -1  1  1  1 -1  1 -1
   1]
 [ 1 -1 -1 -1 -1  1 -1  1  1  1  1 -1  1 -1  1 -1  1 -1 -1 -1  1 -1  1 -1
   1]
 [-1 -1 -1 -1 -1  1  1 -1 -1  1 -1 -1  1 -1 -1  1  1  1  1  1  1  1  1 -1
  -1]
 [ 1 -1 -1  1  1 -1 -1  1  1  1  1  1  1  1 -1  1 -1 -1 -1  1 -1 -1  1  1
   1]
 [-1  1 -1  1  1 -1  1  1 -1 -1  1 -

In [15]:
def hamiltonian (estado,n,m,J):
    #calcula hamiltoniano para un sistema completo con periodicidad n,m, y J de transmisión.
    energy = 0
    for i in range(len(estado)):
        for j in range(len(estado[0])):
            H = estado[i][j]*(estado[(i+1)%n][j] + estado[i][(j+1)%m] + estado[(i-1)%n][j] + estado[i][(j-1)%m])
            energy += -J*H/4
    return energy

H=hamiltonian(a1,7,22,1)

print(H)



-20.0


In [4]:
def magnet (estado):
    #magnetización definida como la suma de todos los spins normalizada a la cantidad de particulas
    B=np.sum(estado)/(len(estado)*len(estado[0]))
    return B

B0=magnet(a1)
print(B0)

-0.05194805194805195


In [4]:
print(len(a1[0]))
a2 = np.ones((7, 22), dtype=int)
a3=a2*-1
print(a3)
H2=hamiltonian(a3,7,22,1)
print(H2)



22
[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
-616


In [ ]:
def MetHas (estado,J,b):
    #algoritmo metropolis-hastings, para un array arbitrario de 1s y -1s.
    for i in range(len(estado)):
        for j in range(len(estado[0])):
            p1 = np.random.randint(0, len(estado))
            p2 = np.random.randint(0, len(estado[0]))
            estado[p1,p2] *= -1
            s=estado[p1,p2]
            # Acá ajusté las posiciones para no sumar sobre toda la matriz sino solo los vecinos
            xpp = (p1 + 1) if (p1 + 1) < len(estado) else 0
            ypp = (p2 + 1) if (p2 + 1) < len(estado[0]) else 0
            xnn = (p1 - 1) if (p1 - 1) >= 0 else (len(estado) - 1)
            ynn = (p2 - 1) if (p2 - 1) >= 0 else (len(estado[0]) - 1)
            R = estado[xpp, p2] + estado[p1, ypp] + estado[xnn, p2] + estado[p1, ynn]

            #variación del Hamiltonian, si cambiamos un estado
            E=2*s*R
            if E < 0:
                estado[p1,p2] *= -1
            elif rand() < np.exp(-E*b):
                estado[p1,p2] *= -1
    return estado 




a4 = MetHas(a1,1,0.1)
print(a4)
   

[[ 1  1  1  1  1 -1  1  1 -1 -1  1  1 -1 -1  1  1  1 -1  1  1  1  1]
 [-1  1 -1 -1 -1  1  1 -1 -1 -1  1  1 -1  1  1  1  1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1  1 -1  1  1 -1 -1 -1  1  1  1  1 -1 -1 -1  1  1 -1 -1]
 [-1 -1 -1 -1  1  1 -1 -1 -1  1 -1 -1 -1 -1  1 -1 -1 -1  1 -1  1 -1]
 [ 1 -1 -1  1  1  1  1  1 -1  1 -1  1  1 -1 -1 -1  1 -1 -1 -1  1  1]
 [ 1 -1 -1 -1 -1  1 -1  1  1 -1 -1 -1  1 -1  1  1 -1 -1  1  1 -1 -1]
 [ 1  1  1  1 -1 -1  1  1  1 -1  1  1  1 -1  1  1 -1 -1  1 -1  1  1]]


In [9]:
def entropIsing(estado):
    #entropia de un array tipo modelo de ising
    W=2**(len(estado)*len(estado[0]))+0.001
    L = np.log(W)
    S=1.38*10**(-23)*L
    return S


In [10]:
entropIsing(a1)

np.float64(1.4730763881259956e-21)

In [44]:
#Setear pasos de temperatura
T_steps = 55
x_dim = 20
y_dim= 12
eqSteps = 1024       #  pasos para equilibrar el algoritmo térmicamente (arbitrario ya que nada me indica que se esta en equilibrio)
mcSteps = 128      #  iteraciones  

T       = np.linspace(0.0001, 1, T_steps); #creando rango de temperaturas y weas vacías pa meterles los datos
E,M,S = np.zeros(T_steps), np.zeros(T_steps), np.zeros(T_steps)
n  = 1.0/(mcSteps*x_dim*y_dim)



In [45]:
#----------------------------------------------------------------------
#  MAIN PART OF THE CODE
#----------------------------------------------------------------------
for tt in range(T_steps):
    E1 = M1 = E2 = M2 = S1 = 0
    config = inicio(x_dim,y_dim)
    iT=1.0/T[tt];
    
    for i in range(eqSteps):         #equilibrar el Met-Has
        MetHas(config,1, iT)

    for i in range(mcSteps):   #hacer integración tipo monte carlo
        MetHas(config,1, iT)           
        Ene = hamiltonian(config,x_dim, y_dim, 1)     
        Mag = magnet(config)        
        Ent = entropIsing(config)

        E1 = E1 + Ene
        M1 = M1 + Mag
        S1 = S1 + Ent

    E[tt] = n*E1        #promedio los valores y lo vuelvo intensivo
    M[tt] = n*M1
    S[tt] = n*S1

In [14]:
for i in range(eqSteps):         # equilibrate
        MetHas(config, 1, 1) 

print(config)

[[ 1  1  1  1 -1 -1  1  1  1  1 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1
   1]
 [ 1  1 -1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1 -1
  -1]
 [-1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1 -1
  -1]
 [-1 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1
  -1]
 [-1 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1
  -1]
 [-1 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1 -1 -1  1  1  1  1  1
   1]
 [-1 -1 -1  1  1  1  1  1 -1 -1  1  1  1  1  1  1 -1 -1 -1  1  1 -1 -1  1
   1]
 [-1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1 -1 -1 -1
  -1]
 [-1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1 -1 -1 -1
  -1]
 [-1 -1  1  1  1  1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1 -1 -1 -1
  -1]
 [-1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1  1  1  1 -1  1  1
  -1]
 [ 1 -1 -1  1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1 -1  1  1  1  1 -1  1  1
   1]
 [ 1 -1 -1  1  1  1 -1 -1  1  1 -1 -1 -1

In [43]:
print(E)


[-0.675      -0.55833333 -0.68333333 -0.56666667 -0.53333333 -0.66666667
 -0.61666667 -0.64166667 -0.56666667 -0.69166667 -0.55       -0.53333333
 -0.54166667 -0.6        -0.59166667 -0.66666667 -0.66666667 -0.63333333
 -0.61666667 -0.59166667 -0.7        -0.6        -0.6        -0.575
 -0.525      -0.50833333 -0.7        -0.51666667 -0.575      -0.56666667
 -0.6        -0.56666667 -0.7        -0.7        -0.65       -0.625
 -0.625      -0.61666667 -0.61666667 -0.63333333 -0.75833333 -0.64166667
 -0.64166667 -0.58333333 -0.61666667 -0.55       -0.65       -0.63333333
 -0.6        -0.76666667 -0.59166667 -0.55833333 -0.575      -0.66666667
 -0.575     ]
